typography_spectrum: 0.20955104334279895
color:
  brandColors:
    - '#ffffff'
    - '#262626'
    - '#565656'
    - '#dadada'
    - '#878787'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: arthursellati
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ARTHUR SELLATI
purpose: []
