name: arthursellati
favicon: null
layout_spectrum: 0.9672388464678079
typography_spectrum: 0.20955104334279895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4336826007347554
  lightness: 0.12855028780177236
  saturation: 0.6962145026773214
  rhythmicContrast: 0.7515840434934944
purpose: []
