name: arthursellati
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20955104334279895
title: ARTHUR SELLATI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262626'
    - '#565656'
    - '#dadada'
    - '#878787'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
