name: arthursellati
favicon: null
layout_spectrum: 0.9672388464678079
typography_spectrum: 0.20955104334279895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262626'
    - '#565656'
    - '#dadada'
    - '#878787'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6962145026773214
  rhythmicContrast: 0.5
purpose: []
